---
title: "PMI_all_lipid_dendrogram"
author: "Melanie Odenkirk"
output: html_document
---

This file includes the lipid circular dendrogram output used to construct Figure 3a of "From Prevention to Disease Perturbations: A Multi-Omic Assessment of Exercise and Myocardial Infarctions" by Odenkirk et al.

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = "", tidy.opts = list(width.cutoff = 60), tidy = TRUE, echo = FALSE, include = FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = 'PMI_EX_data/')
  library(httr)
  library(jsonlite)
  library(fingerprint)
  library(rcdk)
  library(ggplot2)
  library(ggtree)
  library(ape)
  library(phangorn)
  library(limma)
  library(digest)
  library(factoextra)
  library(NbClust)
  library(reshape2)
  library(scales)
  library(dendextend)
```


```{r, include=FALSE}
load("fp_PMI_All lipids.rdata")
tupgma <- upgma(fp.dist, method = "complete")


```


```{r pressure, echo=FALSE, include=FALSE}

mi_fn <- c("PMI_results")

fn <- mi_fn[1]
sig.df <- data.frame(matrix(nrow = 301, ncol = length(mi_fn)))
for( i in 1 : length(mi_fn)) {
  fn <- mi_fn[i]
  df1<- read.csv(paste0(fn, "_neg.csv"))
  df2<- read.csv(paste0(fn, "_pos.csv"))
  df <- rbind(df1, df2)
  sig.df[, i] <- (df$Log2FCBeforevAfter) 
  colnames(sig.df)[i] <- fn
}

sig.df$Lipid <- df$Lipid
sig.df <- sig.df[c(2, 1)]

lipids <- sig.df$Lipid
sig.df$Lipid <- gsub("/", "_", sig.df$Lipid)


sig.df <- unique(sig.df)


rownames(sig.df) <- sig.df$Lipid

sig.df$Lipid <- NULL

sig.df[sig.df == 0] <- NA


breaks <- seq(from=min(range(-3)), to=max(range(3)), length.out=10000)
midpoint <- which.min(abs(breaks - 0))
rampCol1 <- colorRampPalette(c("#002060", "#0d78ca", "#00e8f0"))(midpoint)
rampCol2 <- colorRampPalette(c("#FF4D4D", "red", "darkred"))(10000-(midpoint+1))
rampCols <- c(rampCol1,rampCol2)

```

##Lipid Dendogram

## Integrating code from George
```{r, echo=FALSE}
#color by the property (For dyes it was color) 
sig.df_1 <- sig.df

#load all desc.
cmpds <- read.csv("PMI_LIPID_HG.csv", header= TRUE)

#color by the property (Using HG classification)
sortMat2 = cmpds


#colorby property (Property is desc. col. name like p-value)
HG = cmpds$HG

#cols for three tier plot
#Easy control of color assignments. "Name" = "Color"
#"Name" is the cell value inside original dataframe.

cols10 =c("Car" = "olivedrab3","CE" = "purple3", "Cer" = "black", "DG" = "gold3", "Gal/Glc Cer" = "darkcyan" ,"MG"= "red", "LPC" = "seagreen2", "PC" = "violetred3", "PC O-" = "turquoise2", "PC P-" = "darkorange", "LPE" = "blue", "PE" = "forestgreen", "PE P-" = "salmon", "PI" = "dodgerblue1","SM" = "ghostwhite","TG" = "navy",  "PE O-" = "plum1")


###Adding sunburst effect (heatmap around circ. dend.)
#to_plot with three variables
#note. to create empty rows you need to use " " containers
#Each empty row needs a diff blank container, one space, two space, etc.

to_plot3= (sig.df_1)
                             
names(to_plot3)="PMI_results"
rownames(to_plot3) = rownames(sig.df_1)
```

## Pretty dendrogram

```{r, echo=FALSE, fig.height=16, fig.width=16, message=FALSE, warning=FALSE, include = TRUE}
#Generate Circular Dendrogram
t4 <- ggtree(tupgma, layout="circular", size=1.5) 
#%<+% is a pipe symbol to combine datasets more efficiently=
#merging circ. dend. w/ pvalue color assignments
t4 <- t4 %<+% cmpds +
 geom_tippoint(aes(color=HG), size=3.5, alpha = 0.6, shape = 16)+
  scale_color_manual(values =cols10) +
  theme(legend.position="bottom",legend.text=element_text(size=10))+
  theme(plot.margin = unit(c(0,0,0,0), "cm"))+
  theme(text = element_text(size = 0.01)) +
  geom_treescale(x = NULL, y = NULL, width = 0.5, offset = 30,
                 color = "white", linesize = 1E-100, fontsize = 1E-100)
#plots circular dendrogram with layered heatmap
t4 <- gheatmap(t4, to_plot3[1], offset = 0, width = 0.12, colnames = F)  +
  scale_fill_gradient2(low = rampCol1, high = rampCol2, mid = "white", na.value = "grey70", midpoint = 0)


open_tree(t4, 50) %>% rotate_tree(50)
```




